name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your region

      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://githubworkflow4/ --delete --exclude ".git/*"

      - name: Set S3 bucket policy for public access
        run: |
          aws s3 website s3://githubworkflow4/ --index-document index.html --error-document error.html
